"project_identifier" : "youtrackjetbrains"
"api_key_env" : CROWDIN_API_KEY
"base_path_env" : CROWDIN_BASE_PATH

"preserve_hierarchy": true

files: [
 {
  "source" : "/src/app/translations/default.pot",
  "dest": "/widgets/crowdin-status-widget/default.pot",
  "translation" : "/src/app/translations/crowdin-status-widget_%two_letters_code%.po",
 }
]
